### ISSUE TITLE
Unable to install environment, issue with requirements.txt

### ISSUE THREAD

**Issue by JayanthRR** [epfml/byzantine-robust-noniid-optimizer#1]
requirements.txt has temp paths and leads to the following error.
`Invalid requirement: 'argon2-cffi @ file:///tmp/build/80754af9/argon2-cffi_1613037097816/work'
It looks like a path. Does it exist ?`

Commenting out all the temp paths also doesn't help. It leads to
`Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-f_NX_W/astroid/`

**Comment by liehe** [comment]
Thanks for pointing out the issue. The dependencies of this repository are much less than `requirements.txt`. I tried to create a new environment and test the core package that can run the Exp1.
```
numpy==1.23.0
Pillow==9.1.1
scipy==1.8.1
torch==1.7.1
torchvision==0.8.2
typing-extensions==4.2.0
```
The plotting modules are not installed yet. Let me know if you found other issues.

**Comment by JayanthRR** [comment]
Thank you for the response. I was able to run `exp1`, `exp3` with these minimal dependencies. I guess the others should work fine too.
